## 生成环境
spring:
  profiles: prod
  thymeleaf:
    cache: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
server:
  port: 8161
elastic-mapper:
    onMapper: true